;/*FB_PKG_DELIM*/

__d("PolarisActivityFeedRoot.entrypoint",["JSResourceForInteraction"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){return{queries:{}}},root:c("JSResourceForInteraction")("PolarisActivityFeedRoot.react").__setRef("PolarisActivityFeedRoot.entrypoint")};g["default"]=a}),98);
__d("PolarisClipsTabDesktopContainerDirectQuery$Parameters",["PolarisClipsTabDesktopContainerDirectQuery_instagramRelayOperation","PolarisReelsShareMenu.relayprovider"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("PolarisClipsTabDesktopContainerDirectQuery_instagramRelayOperation"),metadata:{is_distillery:!0},name:"PolarisClipsTabDesktopContainerDirectQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__PolarisReelsShareMenurelayprovider:b("PolarisReelsShareMenu.relayprovider")}}};e.exports=a}),null);
__d("PolarisClipsTabDesktopContainerQuery$Parameters",["PolarisReelsShareMenu.relayprovider"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"7734757436582076",metadata:{},name:"PolarisClipsTabDesktopContainerQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__PolarisReelsShareMenurelayprovider:b("PolarisReelsShareMenu.relayprovider")}}};e.exports=a}),null);
__d("PolarisClipsTabDesktopNonProfiledContainerQuery_instagramRelayOperation",[],(function(a,b,c,d,e,f){e.exports="25725775097067017"}),null);
__d("PolarisClipsTabDesktopNonProfiledContainerQuery$Parameters",["PolarisClipsTabDesktopNonProfiledContainerQuery_instagramRelayOperation","PolarisReelsShareMenu.relayprovider"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("PolarisClipsTabDesktopNonProfiledContainerQuery_instagramRelayOperation"),metadata:{is_distillery:!0},name:"PolarisClipsTabDesktopNonProfiledContainerQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__PolarisReelsShareMenurelayprovider:b("PolarisReelsShareMenu.relayprovider")}}};e.exports=a}),null);
__d("PolarisClipsTabDesktopNonProfiledContent.entrypoint",["JSResourceForInteraction","PolarisClipsTabDesktopNonProfiledContainerQuery$Parameters"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){var b={container_module:"clips_tab_desktop_page_non_profiled"};a.routeProps.media_id!=null&&(b=babelHelpers["extends"]({},b,{chaining_media_id:a.routeProps.media_id,should_refetch_chaining_media:!0}));return{queries:{polarisClipsTapDesktopPageQuery:{options:{},parameters:c("PolarisClipsTabDesktopNonProfiledContainerQuery$Parameters"),variables:{data:b}}}}},root:c("JSResourceForInteraction")("PolarisClipsTabDesktopNonProfiledContainer.react").__setRef("PolarisClipsTabDesktopNonProfiledContent.entrypoint")};b=a;g["default"]=b}),98);
__d("PolarisClipsTabDesktopProfiledContent.entrypoint",["JSResourceForInteraction","PolarisClipsTabDesktopContainerDirectQuery$Parameters","PolarisClipsTabDesktopContainerQuery$Parameters","gkx"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){var b={container_module:"clips_tab_desktop_page"};a.routeProps.media_id!=null&&(b=babelHelpers["extends"]({},b,{chaining_media_id:a.routeProps.media_id,should_refetch_chaining_media:!0}));return{queries:{polarisClipsTapDesktopPageQuery:{options:{},parameters:c("gkx")("1746")?c("PolarisClipsTabDesktopContainerDirectQuery$Parameters"):c("PolarisClipsTabDesktopContainerQuery$Parameters"),variables:{data:b}}}}},root:c("JSResourceForInteraction")("PolarisClipsTabDesktopContainer.react").__setRef("PolarisClipsTabDesktopProfiledContent.entrypoint")};b=a;g["default"]=b}),98);
__d("PolarisClipsTabDesktopRoot.entrypoint",["JSResourceForInteraction","NestedRelayEntryPointBuilderUtils","PolarisClipsTabDesktopNonProfiledContent.entrypoint","PolarisClipsTabDesktopProfiledContent.entrypoint","gkx"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){return{entryPoints:{desktopContainerContent:h(a)},queries:{}}},root:c("JSResourceForInteraction")("PolarisClipsTabDesktopRoot.react").__setRef("PolarisClipsTabDesktopRoot.entrypoint")};function h(a){return a.routeParams.tab!=="following"||c("gkx")("1551")!==!0?d("NestedRelayEntryPointBuilderUtils").NestedRelayEntryPoint({entryPoint:b("PolarisClipsTabDesktopProfiledContent.entrypoint"),entryPointParams:a}):d("NestedRelayEntryPointBuilderUtils").NestedRelayEntryPoint({entryPoint:b("PolarisClipsTabDesktopNonProfiledContent.entrypoint"),entryPointParams:a})}g["default"]=a}),98);
__d("PolarisExploreRoot.entrypoint",["JSResourceForInteraction"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){return{queries:{}}},root:c("JSResourceForInteraction")("PolarisExploreRoot.react").__setRef("PolarisExploreRoot.entrypoint")};g["default"]=a}),98);